services:
  ooye:
    image: git.shork.ch/docker-images/out-of-your-element:latest
    volumes:
      - ./registration.yaml:/usr/src/app/registration.yaml
      - ./ooye.db:/usr/src/app/ooye.db
    ports:
      - 127.0.0.1:6693:6693
    #command: sleep 1800 # For setup
